## Exercici 1

Carregar “data” i "target" del conjunt de dades, i visualitza els 10 primers registres de cadascun.

In [2]:
from sklearn.datasets import load_iris

In [3]:
#defino mi dataframe
iris = load_iris()

# obtengo la data y el target del dataframe iris
data = iris.data
target = iris.target

# Mostrar los 10 primeros registros del conjunto de datos de data y target
print(data[:10])
print(target[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[0 0 0 0 0 0 0 0 0 0]


## Exercici 2

Concatena “data” i “target” en un nou array. Mostra els 5 primers registres.



In [4]:
# subimos la libreria Numpy para poder crear la array
import numpy as np

# Concatenar data y target en un nuevo array (np.column_stack) lo que hace es concatenar y añadirte una columna más 
concatenar_array = np.column_stack((data, target))

# Mostrar los 5 primeros registros del nuevo array
print(concatenar_array[:5])

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


## Exercici 3

Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals.

In [5]:
#como ya tenemos importada la librería numpy continuamos con los siguientes pasos:

# Obtenemos las columnas de longitud del sépalo y longitud del pétalo
sepal_length = data[:, 0]  # Índice 0 corresponde a "sepal length (cm)",esta función nos dirigimos al ídice.
petal_length = data[:, 2]  # Índice 2 corresponde a "petal length (cm)",esta función nos dirigimos al ídice.

# Calcular la media y la desviación estándar
sepal_length_mean = np.mean(sepal_length)
sepal_length_std = np.std(sepal_length)
petal_length_mean = np.mean(petal_length)
petal_length_std = np.std(petal_length)

# Mostrar los resultados con dos decimales utilizamos la función .2f
print(f"Longitud del sépalo - Media: {sepal_length_mean:.2f}, Desviación Estándar: {sepal_length_std:.2f}")
print(f"Longitud del pétalo - Media: {petal_length_mean:.2f}, Desviación Estándar: {petal_length_std:.2f}")

Longitud del sépalo - Media: 5.84, Desviación Estándar: 0.83
Longitud del pétalo - Media: 3.76, Desviación Estándar: 1.76


## Exercici 4

Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior.

Como ya tenemos las columnas del ejercicio anterior, a continuación vamos generar un 
índice aleatorio de 20 registros utilizando np.random.choice y luego seleccionamos los 
registros correspondientes de las columnas de longitud del sépalo y longitud del pétalo. 
Esto nos dará una muestra aleatoria de 20 registros de ambas características.

In [6]:
# primero creamos un índice aleatorio de 20 registros con la función np.random.
random_indices = np.random.choice(len(data), 20, replace=False)

# Seleccionar los 20 registros aleatorios de las columnas de longitud del sépalo y longitud del pétalo, 
#con la función anteriormente creada
random_sepal_length = sepal_length[random_indices]
random_petal_length = petal_length[random_indices]

# Mostrar los registros aleatorios
print("Muestra aleatoria de 20 registros de longitud del sépalo:",random_sepal_length)
print("\nMuestra aleatoria de 20 registros de longitud del pétalo:",random_petal_length)

Muestra aleatoria de 20 registros de longitud del sépalo: [6.1 5.  5.4 4.8 5.5 6.3 5.5 5.9 6.2 5.5 7.2 6.3 6.3 6.3 6.4 4.9 4.9 5.1
 4.9 6.9]

Muestra aleatoria de 20 registros de longitud del pétalo: [5.6 3.5 1.3 1.9 3.8 6.  1.3 4.2 4.8 4.  6.1 4.7 4.9 5.6 5.6 1.5 1.4 1.5
 4.5 4.9]


## Exercici 5

Crea una matriu que mostri: 

• La mitjana de cada característica per espècie. 

• La desviació estàndard de cada característica per espècie.

In [7]:
#Creamos una matriz de ceros de dimensiones 3x2 para almacenar los resultados. 

result_matrix = np.zeros((3, 2)) #((3,2)) significa que tendrá tres filas para las tres especies (Setosa, Versicolor y Virginica) y 
#dos columnas para la media y la desviación estándar.

# Calcular la media y la desviación estándar de cada característica por especie


for species in np.unique(target): #Utilizamos un bucle for para recorrer cada especie (0, 1 y 2).
#Para cada especie, seleccionamos los datos de longitud(length) del sépalo y del pétalo correspondientes 
#utilizando la indexación booleana.
    species_data_sepal = sepal_length[target == species]
    species_data_petal = petal_length[target == species]
    
#Calculamos la media (np.mean) y la desviación estándard (np.std) de ambas características para cada especie.    
    mean_sepal = np.mean(species_data_sepal)
    std_sepal = np.std(species_data_sepal)
    
    mean_petal = np.mean(species_data_petal)
    std_petal = np.std(species_data_petal)
    
#Almacenamos los resultados en la matriz (result_matrix) en las filas correspondientes.    
    result_matrix[species, 0] = mean_sepal
    result_matrix[species, 1] = std_sepal

# Etiquetas para las filas y las columnas de la matriz, o si no, no se entenderá.
species_labels = ['Setosa', 'Versicolor', 'Virginica']
feature_labels = ['Media Sépalo', 'Desviación Sépalo']

#Esto proporciona la media y la desviación estándar de la longitud del sépalo para cada especie. 

# Mostramos la matriz con etiquetas
for i in range(3): 
    for j in range(2): #Usamos bucles (for) anidados para recorrer las filas y las columnas de la matriz result_matrix.
        print(f"{species_labels[i]} - {feature_labels[j]:<17}: {result_matrix[i, j]:.2f}") 
        
#Imprimimos los resultados con formato [i], mostrando la especie, la característica y el valor con dos decimales(.2f).

Setosa - Media Sépalo     : 5.01
Setosa - Desviación Sépalo: 0.35
Versicolor - Media Sépalo     : 5.94
Versicolor - Desviación Sépalo: 0.51
Virginica - Media Sépalo     : 6.59
Virginica - Desviación Sépalo: 0.63


## Exercici 6

• Calcula la quantitat de mostres per espècie.

• Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"

In [10]:
# Creamos una lista de nombres de especies para facilitar la visualización de los resultados.
species_names = ['Setosa', 'Versicolor', 'Virginica']

# Calcular la cantidad de muestras por especie
#Calculamos la cantidad de muestras por especie (Setosa, Versicolor y Virginica).
# np.sum(target == i)cuenta cuántas muestras tienen una etiqueta igual a (i) en el conjunto de datos.
samples_per_species = [np.sum(target == i) for i in range(3)]

# Mostrar la cantidad de muestras por especie
for i, species in enumerate(species_names):
    print(f'{species}: {samples_per_species[i]} muestras')

# Calcular la especie con el valor máximo de media en "sepal length (cm)" 
#Utilizamos un bucle (for) y la función enumerate para recorrer la lista de nombres de especies y la lista de cantidades.
#Mostramos la cantidad de muestras por especie junto con el nombre de la especie.

sepal_length = data[:, 0]  # Índice 0 corresponde a "sepal length (cm)" Extraemos la longitud del sépalo del conjunto de datos.
mean_sepal_length_per_species = [np.mean(sepal_length[target == i]) for i in range(3)] #Calculamos la media de la longitud del sépalo para cada especie y almacenamos estos valores en mean_sepal_length_per_species.

#Encontramos la especie con el valor máximo de media utilizando np.argmax y mostramos el resultado junto con su valor correspondiente.
max_mean_sepal_length = np.max(mean_sepal_length_per_species)
max_mean_species = species_names[np.argmax(mean_sepal_length_per_species)]

print(f'\nLa especie con el valor máximo de media en "sepal length (cm)" es {max_mean_species} con una media de {max_mean_sepal_length:.2f} cm.')


Setosa: 50 muestras
Versicolor: 50 muestras
Virginica: 50 muestras

La especie con el valor máximo de media en "sepal length (cm)" es Virginica con una media de 6.59 cm.


## Exercici 7

• Calcula la matriu de correlació entre les variables.

• Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho. 

• Troba la mostra amb els pètals més grans.

In [12]:
import pandas as pd #importamos la biblioteca Pandas para cargar el conjunto de dats iris.

# Cargamos el conjunto de datos Iris y creamos un DataFrame de Pandas para facilitar la manipulación de los datos
df = pd.DataFrame(data, columns=iris.feature_names)

# Calculamos la matriz de correlación de las características utilizando el método corr() de Pandas, 
# el cual calcula la correlación entre columnas numéricas de un conjunto de datos.
correlation_matrix = df.corr()

# Filtrar los valores mayores a la media de la longitud de los pétalos 
mean_petal_length = df['petal length (cm)'].mean()
filtered_data = df[df['petal length (cm)'] > mean_petal_length]

# Mostrar la matriz de correlación
print("Matriz de correlación:")
print(correlation_matrix)

# Mostrar los valores filtrados
print("\nValores mayores a la media de la longitud de los pétalos:")
print(filtered_data)

# Encontramos la muestra con los pétalos más largos utilizando la función max() 
#de Pandas en la columna "petal length (cm)" y mostramos la muestra resultante.
max_petal_length_sample = df[df['petal length (cm)'] == df['petal length (cm)'].max()]

print("\nMuestra con los pétalos más largos:")
print(max_petal_length_sample)

Matriz de correlación:
                   sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000  

Valores mayores a la media de la longitud de los pétalos:
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
50                 7.0               3.2                4.7               1.4
51                 6.4               3.2                4.5               1.5
52                 6.9               3.1                4.9               1.5
53                 5.5        

## Exercici 8

Troba l'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals.

In [18]:
#Utilizamos el conjunto de datos Iris previamente cargado y extraemos las longitudes de los sépalos
#y los pétalos en las variables sepal_length y petal_length.

# Calculamos la longitud promedio de los sépalos y los pétalos para cada especie. Utilizamos numpy
sepal_length = data[:, 0]  # Índice 0 corresponde a "sepal length (cm)"
petal_length = data[:, 2]  # Índice 2 corresponde a "petal length (cm)"


#esta fórmula calcula la longitud promedio de los pétalos para cada una de las tres especies en el conjunto 
#de datos Iris, utilizando un bucle para iterar a través de las especies y calcular la media de las longitudes 
#de los pétalos correspondientes a cada especie.

mean_sepal_length = [np.mean(sepal_length[target == i]) for i in range(3)] 
mean_petal_length = [np.mean(petal_length[target == i]) for i in range(3)]
#np.mean estamos calculando la longitud promedio de los pétalos para una especie específica / 
#[np.mean(petal_length[target == i]) for i in range(3)] combina todo esto en un bucle, donde para cada valor de 'i' 
#en el rango de 0 a 2, calculamos la longitud promedio de los pétalos para la especie correspondiente. 
#El resultado es una lista de las longitudes promedio de los pétalos para las tres especies en el conjunto de datos Iris.


# Calculamos la diferencia entre la longitud promedio de sépalos y pétalos
differences = np.abs(np.array(mean_sepal_length) - np.array(mean_petal_length))
# calcula la diferencia absoluta entre las medias de longitud del sépalo y del pétalo para cada especie en el conjunto de
#datos Iris, y almacena esas diferencias en un arreglo NumPy llamado 'differences'.

# Encontramos la especie con la mayor diferencia
max_difference_species = np.argmax(differences)
#se utiliza para identificar la especie en el conjunto de datos Iris que tiene la mayor diferencia entre las longitudes promedio
#de los sépalos y los pétalos, y almacena el índice de esa especie en la variable max_difference_species.

# Mostramos la especie con la mayor diferencia
species_names = ['Setosa', 'Versicolor', 'Virginica']
print(f'Especie con la mayor diferencia: {species_names[max_difference_species]}')


Especie con la mayor diferencia: Setosa
